/**
 * Client-side PDF export styled like the create-invoice layout:
 * business name + logo (top left), morapay (top right), line items + totals,
 * notes and terms (full width), then optional pay-by-link block (bottom-right column:
 * “Scan to pay invoice”, URL, QR, copy) before footer attribution.
 */

import type { SerializedInvoice } from "@/lib/data-invoices";
import { formatInvoiceCurrency } from "@/lib/data-invoices";
import { format } from "date-fns";
import { PLATFORM_PRIMARY_HEX } from "@/lib/platform-theme";
import { buildPaymentLinkPublicUrl } from "@/lib/merchant-commerce-helpers";

export type InvoicePdfBranding = {
  businessName: string;
  logoUrl?: string | null;
};

export type ExportInvoicePdfOptions = {
  /** Payer checkout origin (no trailing slash), e.g. from Core meta — required to show invoice pay QR. */
  checkoutBaseUrl?: string | null;
};

const LINE_H9 = 4.4;
const LINE_H8 = 3.6;

function hexToRgb(hex: string): [number, number, number] {
  const m = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex.trim());
  if (!m) return [2, 52, 54];
  return [parseInt(m[1], 16), parseInt(m[2], 16), parseInt(m[3], 16)];
}

function blobToDataUrl(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const r = new FileReader();
    r.onload = () => resolve(String(r.result));
    r.onerror = () => reject(new Error("read failed"));
    r.readAsDataURL(blob);
  });
}

async function loadImageDataUrl(url: string): Promise<string | null> {
  const trimmed = url.trim();
  if (!trimmed) return null;
  try {
    const res = await fetch(trimmed, { mode: "cors", credentials: "omit" });
    if (!res.ok) return null;
    const blob = await res.blob();
    if (!blob.type.startsWith("image/")) return null;
    return blobToDataUrl(blob);
  } catch {
    return null;
  }
}

async function loadMorapayLogoDataUrl(): Promise<string | null> {
  if (typeof window === "undefined") return null;
  const url = new URL("/logo.jpg", window.location.origin).href;
  return loadImageDataUrl(url);
}

function imageFormatFromDataUrl(dataUrl: string): "JPEG" | "PNG" | "WEBP" {
  if (dataUrl.includes("image/png")) return "PNG";
  if (dataUrl.includes("image/webp")) return "WEBP";
  return "JPEG";
}

async function qrDataUrlForUrl(text: string): Promise<string | null> {
  try {
    const QR = (await import("qrcode")).default;
    return await QR.toDataURL(text, {
      margin: 1,
      width: 320,
      color: { dark: PLATFORM_PRIMARY_HEX, light: "#ffffff" },
    });
  } catch {
    return null;
  }
}

export async function exportInvoiceToPdf(
  invoice: SerializedInvoice,
  branding: InvoicePdfBranding,
  options?: ExportInvoicePdfOptions
): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const autoTable = (await import("jspdf-autotable")).default;

  const checkoutBase = options?.checkoutBaseUrl?.trim().replace(/\/$/, "") ?? "";
  const pl = invoice.paymentLink;
  const checkoutCode = pl?.publicCode?.trim() || pl?.slug?.trim() || "";
  const payUrl =
    pl && checkoutBase && checkoutCode
      ? buildPaymentLinkPublicUrl(checkoutCode, checkoutBase)
      : "";

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 14;
  const contentW = pageW - margin * 2;
  const primaryRgb = hexToRgb(PLATFORM_PRIMARY_HEX);
  const footerText = `This invoice was generated by ${branding.businessName} through morapay`;

  const [morapayLogo, businessLogo, qrData] = await Promise.all([
    loadMorapayLogoDataUrl(),
    branding.logoUrl ? loadImageDataUrl(branding.logoUrl) : Promise.resolve(null),
    payUrl ? qrDataUrlForUrl(payUrl) : Promise.resolve(null),
  ]);

  let y = margin;

  // --- Header: business (left) | morapay (right) ---
  const headerTop = y;
  const logoBox = 11;
  let leftX = margin;

  if (businessLogo) {
    try {
      doc.addImage(
        businessLogo,
        imageFormatFromDataUrl(businessLogo),
        leftX,
        headerTop,
        logoBox,
        logoBox
      );
      leftX += logoBox + 3;
    } catch {
      // skip broken image
    }
  }

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text(branding.businessName, leftX, headerTop + 7);
  doc.setFont("helvetica", "normal");

  // const rightEdge = pageW - margin;
  // const moraLabel = "morapay";
  // doc.setFontSize(10);
  // doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
  // const moraTextW = doc.getTextWidth(moraLabel);
  // const logoSize = 8;
  // if (morapayLogo) {
  //   try {
  //     const imgLeft = rightEdge - moraTextW - 2 - logoSize;
  //     doc.addImage(
  //       morapayLogo,
  //       imageFormatFromDataUrl(morapayLogo),
  //       imgLeft,
  //       headerTop,
  //       logoSize,
  //       logoSize
  //     );
  //   } catch {
  //     // skip
  //   }
  // }
  // doc.text(moraLabel, rightEdge, headerTop + 6, { align: "right" });
  // doc.setTextColor(15, 23, 42);

  y = Math.max(headerTop + logoBox, headerTop + 10) + 6;

  // --- Title: "Invoice" on first line; number + status on second (omit "Draft" label) ---
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Invoice", margin, y);
  y += 6;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 116, 139);
  const statusLine =
    invoice.status === "Draft"
      ? invoice.invoiceNumber
      : `${invoice.invoiceNumber} · ${invoice.status}`;
  doc.text(statusLine, margin, y);
  doc.setTextColor(15, 23, 42);
  y += 8;

  // --- Two columns: billed / billing | subject ---
  const colGap = 6;
  const colW = (contentW - colGap) / 2;
  const ySectionStart = y;
  const col2X = margin + colW + colGap;

  let yLeft = ySectionStart;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.setFont("helvetica", "normal");
  doc.text("Billed to", margin, yLeft);
  yLeft += LINE_H8;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(9);
  const billedLines = doc.splitTextToSize(invoice.billedTo || "—", colW);
  doc.text(billedLines, margin, yLeft);
  yLeft += billedLines.length * LINE_H9 + 4;

  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("Billing address", margin, yLeft);
  yLeft += LINE_H8;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(9);
  const addr = (invoice.billingDetails || "").trim() || "—";
  const addrLines = doc.splitTextToSize(addr, colW);
  doc.text(addrLines, margin, yLeft);
  yLeft += addrLines.length * LINE_H9;

  let yRight = ySectionStart;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("Subject", col2X, yRight);
  yRight += LINE_H8;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(9);
  const subjectLines = doc.splitTextToSize((invoice.subject || "Invoice").trim(), colW);
  doc.text(subjectLines, col2X, yRight);
  yRight += subjectLines.length * LINE_H9;

  y = Math.max(yLeft, yRight) + 8;

  // --- Metadata ---
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  const metaX = margin;
  doc.text(`Invoice number: ${invoice.invoiceNumber}`, metaX, y);
  y += 4;
  doc.text(`Currency: ${invoice.currencyLabel ?? invoice.currency}`, metaX, y);
  y += 4;
  doc.text(`Issued: ${format(new Date(invoice.issued), "d MMM yyyy")}`, metaX, y);
  y += 4;
  doc.text(`Due date: ${format(new Date(invoice.dueDate), "d MMM yyyy")}`, metaX, y);
  y += 4;
  if (invoice.discountPercent > 0) {
    doc.text(`Discount: ${invoice.discountPercent}%`, metaX, y);
    y += 4;
  }
  y += 4;

  const cur = invoice.currency;
  const body = invoice.lineItems.map((li) => [
    li.productName,
    String(li.qty),
    formatInvoiceCurrency(li.unitPrice, cur),
    formatInvoiceCurrency(li.amount, cur),
  ]);

  autoTable(doc, {
    startY: y,
    head: [["Description", "Qty", "Price", "Amount"]],
    body,
    margin: { left: margin, right: margin, bottom: 16 },
    styles: {
      fontSize: 9,
      cellPadding: { top: 2, right: 2, bottom: 2, left: 2 },
      textColor: [15, 23, 42],
    },
    headStyles: {
      fillColor: primaryRgb,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8,
    },
    columnStyles: {
      0: { cellWidth: contentW - 52 },
      1: { halign: "right", cellWidth: 16 },
      2: { halign: "right", cellWidth: 18 },
      3: { halign: "right", cellWidth: 18 },
    },
  });

  const docWithTable = doc as typeof doc & {
    lastAutoTable?: { finalY: number };
  };
  let cursorY = (docWithTable.lastAutoTable?.finalY ?? y) + 6;

  // --- Totals ---
  const totalsX = pageW - margin - 55;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("Subtotal", totalsX, cursorY);
  doc.setTextColor(15, 23, 42);
  doc.text(
    `${formatInvoiceCurrency(invoice.subtotal, cur)} ${cur}`,
    pageW - margin,
    cursorY,
    { align: "right" }
  );
  cursorY += 5;
  if (invoice.discountPercent > 0) {
    doc.setTextColor(16, 185, 129);
    doc.text(`Discount (${invoice.discountPercent}%)`, totalsX, cursorY);
    doc.text(
      `−${formatInvoiceCurrency(invoice.discountAmount, cur)} ${cur}`,
      pageW - margin,
      cursorY,
      { align: "right" }
    );
    doc.setTextColor(15, 23, 42);
    cursorY += 5;
  }
  cursorY += 2;
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Amount due", totalsX, cursorY);
  doc.text(
    `${formatInvoiceCurrency(invoice.amountDue, cur)} ${cur}`,
    pageW - margin,
    cursorY,
    { align: "right" }
  );
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  cursorY += 10;

  const FOOTER_RESERVE_MM = 22;
  const PAY_COL_W = 78;
  const qrMm = 32;
  const urlLineH = 3.6;

  const notesText = (invoice.notesContent || "").trim() || "—";
  const termsText = (invoice.termsAndConditions || "").trim() || "—";
  const notesLinesMeasured = doc.splitTextToSize(notesText, contentW);
  const termsLinesMeasured = doc.splitTextToSize(termsText, contentW);
  const notesBlockH = LINE_H8 + (notesLinesMeasured.length || 1) * LINE_H9 + 6;
  const termsBlockH = LINE_H8 + (termsLinesMeasured.length || 1) * LINE_H9 + 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  const paymentUrlLines =
    payUrl && qrData ? doc.splitTextToSize(payUrl, PAY_COL_W) : [];
  doc.setFontSize(9);
  const paymentBlockEstimate =
    payUrl && qrData
      ? 7 +
        Math.max(1, paymentUrlLines.length) * urlLineH +
        4 +
        qrMm +
        (pl?.amount != null && Number.isFinite(pl.amount) ? 6 : 0) +
        14 +
        6
      : pl && !checkoutBase
        ? 14
        : 0;

  if (cursorY + notesBlockH + termsBlockH + paymentBlockEstimate > pageH - FOOTER_RESERVE_MM) {
    doc.addPage();
    cursorY = margin;
  }

  // --- Notes (full width), after amount due ---
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("Notes to customer", margin, cursorY);
  cursorY += LINE_H8;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(9);
  const notesLines = doc.splitTextToSize(notesText, contentW);
  if (cursorY + notesLines.length * LINE_H9 > pageH - FOOTER_RESERVE_MM) {
    doc.addPage();
    cursorY = margin;
  }
  doc.text(notesLines, margin, cursorY);
  cursorY += notesLines.length * LINE_H9 + 6;

  // --- Terms (full width) ---
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text("Terms and conditions", margin, cursorY);
  cursorY += LINE_H8;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(9);
  const termsLines = doc.splitTextToSize(termsText, contentW);
  if (cursorY + termsLines.length * LINE_H9 > pageH - FOOTER_RESERVE_MM) {
    doc.addPage();
    cursorY = margin;
  }
  doc.text(termsLines, margin, cursorY);
  cursorY += termsLines.length * LINE_H9 + 8;

// --- Pay online: bottom-right column before footer (no top separator) ---
if (payUrl && qrData) {
  const payX = pageW - margin - PAY_COL_W;
  const centerColX = payX + (PAY_COL_W / 2); // The exact mathematical center of the right column
  
  const minPayH =
    7 +
    Math.max(1, paymentUrlLines.length) * urlLineH +
    4 +
    qrMm +
    (pl?.amount != null && Number.isFinite(pl.amount) ? 6 : 0) +
    14;
    
  if (cursorY + minPayH > pageH - FOOTER_RESERVE_MM) {
    doc.addPage();
    cursorY = margin;
  }

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  
  // Center the "Scan to pay invoice" title
  doc.text("Scan to pay invoice", centerColX, cursorY, { align: "center" });
  cursorY += 6;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(51, 65, 85);
  
  if (cursorY + paymentUrlLines.length * urlLineH + qrMm > pageH - FOOTER_RESERVE_MM) {
    doc.addPage();
    cursorY = margin;
  }
  
  // Center the URL lines
  for (let i = 0; i < paymentUrlLines.length; i++) {
      doc.text(paymentUrlLines[i], centerColX, cursorY, { align: "center" });
      cursorY += urlLineH;
  }
  cursorY += 3;

  // Center the QR Code
  const qrLeft = centerColX - (qrMm / 2);
  if (cursorY + qrMm > pageH - FOOTER_RESERVE_MM) {
    doc.addPage();
    cursorY = margin;
  }
  try {
    doc.addImage(qrData, "PNG", qrLeft, cursorY, qrMm, qrMm);
  } catch {
    doc.setFontSize(8);
    doc.text("(QR could not be embedded)", centerColX, cursorY + 4, { align: "center" });
  }
  cursorY += qrMm + 4;

  // Center the Amount
  if (pl?.amount != null && Number.isFinite(pl.amount)) {
    if (cursorY + 8 > pageH - FOOTER_RESERVE_MM) {
      doc.addPage();
      cursorY = margin;
    }
    doc.setFontSize(9);
    doc.setTextColor(15, 23, 42);
    doc.text(
      `${formatInvoiceCurrency(pl.amount, pl.currency || cur)} ${pl.currency || cur}`,
      centerColX,
      cursorY,
      { align: "center" }
    );
    cursorY += 5;
  }

  // Center the Blurb
  const blurb = "Pay with tokens from supported networks on checkout.";
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  const blurbLines = doc.splitTextToSize(blurb, PAY_COL_W);
  if (cursorY + blurbLines.length * urlLineH + 6 > pageH - FOOTER_RESERVE_MM) {
    doc.addPage();
    cursorY = margin;
  }
  
  for (let i = 0; i < blurbLines.length; i++) {
      doc.text(blurbLines[i], centerColX, cursorY, { align: "center" });
      cursorY += urlLineH;
  }
  cursorY += 2;

  // Align "Powered by morapay" directly under the centered stack
  doc.setTextColor(primaryRgb[0], primaryRgb[1], primaryRgb[2]);
  doc.text("Powered by morapay", centerColX, cursorY, { align: "center" });
  
} else if (pl && !checkoutBase) {
  if (cursorY + 12 > pageH - FOOTER_RESERVE_MM) {
    doc.addPage();
    cursorY = margin;
  }
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  doc.text(
    "Configure checkout base URL to include a pay-by-link QR on this export.",
    margin,
    cursorY,
    { maxWidth: contentW }
  );
  cursorY += 8;
}
  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    doc.setFontSize(7.5);
    doc.setTextColor(100, 116, 139);
    doc.setFont("helvetica", "normal");
    doc.text(footerText, pageW / 2, pageH - 8, {
      align: "center",
      maxWidth: contentW,
    });
    doc.setTextColor(15, 23, 42);
  }

  doc.save(`invoice-${invoice.invoiceNumber}.pdf`);
}
